### ISSUE TITLE
ipa报错

### ISSUE THREAD

**Issue by AimerW** [akl7777777/free-chatgpt-client-pub#1]
15.4.1 ios  自签名的时候显示ipa损坏了

**Comment by akl7777777** [comment]
@AimerW 你好,感谢反馈,现在1.1.7版本已修复,烦请下载安装再试试  https://github.com/akl7777777/free-chatgpt-client-mobile-pub/releases/download/v1.1.7/ChatGPTMobile_v1.1.7.ipa

**Comment by akl7777777** [comment]
该问题已修复,先关了哈,后面有问题再开; 最新版的ios https://github.com/akl7777777/free-chatgpt-client-mobile-pub/releases/tag/v1.2.5
