### ISSUE TITLE
2.1.1 输入框，发送，聊天模式，重置聊天，导出markdown都无法用鼠标点击。

### ISSUE THREAD

**Issue by alley80** [akl7777777/free-chatgpt-client-pub#12]
新更新的2.1.1版本 输入框，发送，聊天模式，重置聊天，导出markdown都无法用鼠标点击。
线路选择可以用鼠标点击。
不过用键盘的tab键可以切换选区来操作。但是这太麻烦啦
macos13.1  m1 Macbook air

**Comment by akl7777777** [comment]
已修复请更新2.1.2
