### ISSUE TITLE
可不可以引入代码高亮

### ISSUE THREAD

**Issue by gaoxuxu110** [akl7777777/free-chatgpt-client-pub#14]

**Comment by akl7777777** [comment]
可以,正在研究啊.我也想要高亮...我每天都拿来写代码

**Comment by as7212325** [comment]
+1 现在看着费眼睛

**Comment by akl7777777** [comment]
@gaoxuxu110 @as7212325 代码高亮已经做好了,更新一下最新的包 https://github.com/akl7777777/free-chatgpt-client-pub/releases/tag/v3.2.2

![image](https://user-images.githubusercontent.com/84266551/236438246-9bb4f9f2-c9d7-4807-8670-3a107f8e4450.png)

**Comment by skymouses** [comment]
> @gaoxuxu110 @as7212325 代码高亮已经做好了,更新一下最新的包 https://github.com/akl7777777/free-chatgpt-client-pub/releases/tag/v3.2.2
> 
> ![image](https://user-images.githubusercontent.com/84266551/236438246-9bb4f9f2-c9d7-4807-8670-3a107f8e4450.png)

牛的
