### ISSUE TITLE
希望引入客户端在线更新功能

### ISSUE THREAD

**Issue by varGengYang** [akl7777777/free-chatgpt-client-pub#15]

**Comment by akl7777777** [comment]
有啊,一直就有在线更新功能..如图左上角选择关于,检查更新 
<img width="199" alt="image" src="https://user-images.githubusercontent.com/84266551/233817731-c52f50c6-1e4c-4a8c-accb-53f89d279dd5.png">

**Comment by varGengYang** [comment]
是我眼拙了，没注意看
