### ISSUE TITLE
导出md文件怎么只记录了问题，没有回答内容呢？

### ISSUE THREAD

**Issue by gapore** [akl7777777/free-chatgpt-client-pub#19]
[test.md](https://github.com/akl7777777/free-chatgpt-client-pub/files/11414202/test.md)
如题

**Comment by akl7777777** [comment]
导出的功能已经全面升级了,建议升级最新版客户端体验  https://github.com/akl7777777/free-chatgpt-client-pub/releases/tag/v3.3.0
