### ISSUE TITLE
linux版本报错

### ISSUE THREAD

**Issue by txyxy** [akl7777777/free-chatgpt-client-pub#3]
您好，感谢您的分享！

我在Ubuntu18.04下安装报错：
Error in file "/usr/share/applications/sitemaker.desktop": "" is an invalid MIME type ("" does not contain a subtype)
Error in file "/usr/share/applications/navvis-remote-support-icon.desktop": "" is an invalid MIME type ("" does not contain a subtype)

请问是不是是Ubuntu版本太低了？

**Comment by txyxy** [comment]
刚刚我测试了，可以用，速度也挺快的。报错的地方应该是图标那里有点问题。
再次感谢您的分享！

**Comment by akl7777777** [comment]
好的,我研究下打包的图标是不是有问题..

**Comment by akl7777777** [comment]
@txyxy 我改了下打包命令,图标的问题帮忙看下是否修复,下载最新版 https://github.com/akl7777777/free-chatgpt-client-pub/releases/download/v1.5.5/OpenAi-ChatGPT_1.5.5_amd64.deb

**Comment by txyxy** [comment]
我重新安装了1.5.5版本的，发现还是和之前一样，安装的图标是这样的：
![1](https://user-images.githubusercontent.com/31716481/228404546-87bba631-4754-40ff-a723-6c6c90c81fd4.png)
其它没什么问题，不影响正常使用。
另外，发现GPT-4经常连接不上。。

**Comment by akl7777777** [comment]
试试1.5.8  我刚刚在linux mint 上面安装好像没报错.不过图标确实没有
