### ISSUE TITLE
为什么长文翻译不翻译呢？

### ISSUE THREAD

**Issue by zhl111** [akl7777777/free-chatgpt-client-pub#31]
多少文字都可以吗？为什么几乎没有什么可以支持快速长文翻译的线路呢？翻译完导出只能是图片格式或html格式？右键全选竟然把界面文字都选中了？

**Comment by akl7777777** [comment]
现在加了一个复制的按钮,可以在软件中试试

**Comment by akl7777777** [comment]
用线路编号在10之前的试试,比如海外7,国内4,我刚刚试过都是可以的
