### ISSUE TITLE
hello why gpt 4  option (is it restricted to code only?)not responding in english and please put ai graphics in english also please add english in gpt 4 also please

### ISSUE THREAD

**Issue by ramanujamkanduri** [akl7777777/free-chatgpt-client-pub#4]

**Comment by ramanujamkanduri** [comment]
Ok thank you for reply please add gpt 4 also

**Comment by ramanujamkanduri** [comment]
Ok thank you for reply please add gpt 4 also

**Comment by akl7777777** [comment]
There are now 2 new nodes that support GPT4, to be precise there are three, and one of them has a daily limit for POE.
![image](https://user-images.githubusercontent.com/84266551/233245517-de8b107b-c6d4-4441-b352-e8ebf09a6937.png)
