### ISSUE TITLE
你好 最新版本的报错

### ISSUE THREAD

**Issue by wangkangfeng1999** [akl7777777/free-chatgpt-client-pub#5]
系统版本：
![image](https://user-images.githubusercontent.com/68324194/228713025-03878609-73b5-41ce-8165-2180e8b5d1f8.png)

报错截图：
![image](https://user-images.githubusercontent.com/68324194/228712828-01f2ae5d-6e44-499a-ba1a-0c6c3a5c2d0e.png)

**Comment by akl7777777** [comment]
@wangkangfeng1999 你好,感谢反馈,刚刚加急修复了1.5.9版本,麻烦更新下再试试,或者切换一个站点再试试,更新地址在这里https://github.com/akl7777777/free-chatgpt-client-pub/releases/tag/v1.5.9
