### ISSUE TITLE
1.76版本 mac运行出错？

### ISSUE THREAD

**Issue by alley80** [akl7777777/free-chatgpt-client-pub#7]
openAI-ChatGPT将对你的电脑造成伤害，你应该将它移到废纸篓？？？

**Comment by akl7777777** [comment]
备注 : MacOS如果打不开需要开启任意来源

打开【启动台】，选择【终端】，输入：

sudo spctl  --master-disable
然后回车，继续输入密码（密码输入时是不可见的），然后回车。

然后在进入设置,隐私,安全,勾选任何来源
<img width="751" alt="image" src="https://user-images.githubusercontent.com/84266551/230526628-534ca938-22e0-469f-a02a-abc083a7d9c0.png">

然后点击打开软件后,如果再次提示此信息,就再进入设置,隐私,安全,允许就可以了,这个问题可能是我这个包打的有问题,我一会更新一个新版你再试试

**Comment by alley80** [comment]
试过了不行。不过你的1.78ok啦

**Comment by akl7777777** [comment]
好的,可能是我打包的问题,现在已经升级2.0.0版本,支持AI画图了 https://github.com/akl7777777/free-chatgpt-client-pub/releases/tag/v2.0.0
