### ISSUE TITLE
绘画功能完全不着边际

### ISSUE THREAD

**Issue by zhl111** [akl7777777/free-chatgpt-client-pub#8]
这个unsplash API 能换成别的吗？生成的图片与我给的prompt完全不相关

**Comment by akl7777777** [comment]
@zhl111 你好,感谢反馈,现在已经支持 真·AI画图功能,请下载2.0.0版本,赶紧体验吧 https://github.com/akl7777777/free-chatgpt-client-pub/releases/tag/v2.0.0
